name: My first Pipeline

on:
  push:

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: build image
          run: docker build -t PraiseAddy2022/myprofile .
        - name: list images
          run:   docker images  

 

      